version: '3.8'
services:
  front:
    build: .
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge
    external: true
